# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NebulaPki < Formula
  desc "Declarative wrapper around nebula-cert"
  homepage "https://github.com/anverse/nebula-pki"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/anverse/nebula-pki/releases/download/v0.1.2/nebula-pki_0.1.2_darwin_amd64.tar.gz"
      sha256 "5a10ecb64d151bce74e5cb4302a38696605a775beb48b484afa190ed3ad525db"

      define_method(:install) do
        bin.install "nebula-pki"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/anverse/nebula-pki/releases/download/v0.1.2/nebula-pki_0.1.2_darwin_arm64.tar.gz"
      sha256 "fe46c9e168b2bd68d2e604156a0a196153f59574db7e0bd06ba4484a94a9b6d6"

      define_method(:install) do
        bin.install "nebula-pki"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/anverse/nebula-pki/releases/download/v0.1.2/nebula-pki_0.1.2_linux_amd64.tar.gz"
      sha256 "2ad49bcc78225f79c396cb9ee13449fa4725d85e8188116ff15130e8df6027f8"
      define_method(:install) do
        bin.install "nebula-pki"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anverse/nebula-pki/releases/download/v0.1.2/nebula-pki_0.1.2_linux_arm64.tar.gz"
      sha256 "51b7d2c16fa32e986caffbf5b888f0d81faa7a81ebf6fb19120ab9af09427d1a"
      define_method(:install) do
        bin.install "nebula-pki"
      end
    end
  end

  test do
    system "#{bin}/nebula-pki", "--version"
  end
end
