# typed: false
# frozen_string_literal: true

# This formula is regenerated by GoReleaser on every tagged release.
# Until the first release runs, this stub exists so `brew tap
# anverse/nebula-pki` resolves. It intentionally points at a placeholder
# version; the first `goreleaser release` will overwrite this file with
# per-platform URLs and sha256 sums for every published archive.
class NebulaPki < Formula
  desc "Declarative wrapper around nebula-cert"
  homepage "https://github.com/anverse/nebula-pki"
  version "0.0.0"
  license "MIT"

  # Placeholder — GoReleaser replaces this section with per-arch
  # `on_macos` / `on_linux` blocks pointing at the released archives.
  url "https://github.com/anverse/nebula-pki/archive/refs/tags/v0.0.0.tar.gz"
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"

  def install
    bin.install "nebula-pki"
  end

  test do
    assert_match "dev", shell_output("#{bin}/nebula-pki --version")
  end
end
